### ISSUE TITLE
Delete a folder

### ISSUE THREAD

**Issue by Robinouh** [Garethp/php-ews#126]
Hi,

I am trying to delete a folder with the following code:
```
use garethp\ews\API\Enumeration\DistinguishedFolderIdNameType;

$api = MailAPI::withUsernameAndPassword($host, $login, $password);

$folders = $api->getChildrenFolders(DistinguishedFolderIdNameType::MESSAGE_ROOT);

$api->deleteFolder($folders[$folderId]->getFolderId());
```

It seems simple but it doesn't work.

Of course, the _folderId_ variable is the location of the folder that I created and that I want to delete.

Could you help me?

Thank you.

**Comment by Garethp** [comment]
What's the error that you're getting?

**Comment by Robinouh** [comment]
Just a simple error 500, no error message is displayed.

**Comment by Robinouh** [comment]
Effectively, I activated PHP errors and I get this:

```
Fatal error:  Uncaught Error: Call to undefined function garethp\ews\garethp\ews\Utilities\getFolderIds() in C:\Apache24\htdocs\new-app-v4\app\library\garethp\php-ews\src\API.php:227
Stack trace:
#0 C:\Apache24\htdocs\new-app-v4\app\library\garethp\php-ews\src\API.php(222): garethp\ews\API->deleteFolders(Object(garethp\ews\API\Type\FolderIdType), Array)
#1 C:\Apache24\htdocs\new-app-v4\app\controllers\MailBoxController.php(66): garethp\ews\API->deleteFolder(Object(garethp\ews\API\Type\FolderIdType))
#2 [internal function]: MailBoxController->indexAction()
#3 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(MailBoxController), 'indexAction', Array)
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 C:\Apache24\htdocs\new-app-v4\public\index.php(36): Phalcon\Mvc\Application->handle()
#6 {main}
  thrown in C:\Apache24\htdocs\new-app-v4\app\library\garethp\php-ews\src\API.php on line 227
```

However the function _getFolderIds_ is correctly defined.

I specify that I use the latest version (_0.9.6 - TBD_).
