### ISSUE TITLE
Public Calendar - retrieving items

### ISSUE THREAD

**Issue by jbostoen** [Garethp/php-ews#131]
I'm using this example: https://github.com/Garethp/php-ews/blob/master/examples/calendar/workingWithPublicCalendars.php

However, after the line "Perform operations on public folders as normal from here on out" things doesn't seem to work well for me. listChanges() works, but I can't call  $calendar->getCalendarItems('12:00 PM') on it?

`<b>Fatal error</b>:  Uncaught SoapFault exception: [a:ErrorInternalServerError] An internal server error occurred. The operation failed. in C:\xampp\htdocs\garethp-php-ews\vendor\garethp\php-ews\src\API\NTLMSoapClient.php:118
Stack trace:
#0 C:\xampp\htdocs\garethp-php-ews\vendor\garethp\php-ews\src\API\NTLMSoapClient.php(118): SoapClient-&gt;__call('FindItem', Array)
#1 C:\xampp\htdocs\garethp-php-ews\vendor\garethp\php-ews\src\API\ExchangeWebServices\MiddlewareFactory.php(18): garethp\ews\API\NTLMSoapClient-&gt;__call('FindItem', Array)
#2 C:\xampp\htdocs\garethp-php-ews\vendor\garethp\php-ews\src\API\ExchangeWebServices.php(497): garethp\ews\API\ExchangeWebServices-&gt;garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#3 C:\xampp\htdocs\garethp-php-ews\vendor\garethp\php-ews\src\API\ExchangeWebServices\MiddlewareFactory.php(32): garethp\ews\API\ExchangeWebServices-&gt;garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#4 C:\xampp\htdocs\garethp-php-ews\vendor\gareth in <b>C:\xampp\htdocs\garethp-php-ews\vendor\garethp\php-ews\src\API\NTLMSoapClient.php</b> on line <b>118</b><br />
`

**Comment by jbostoen** [comment]
Please? How would I go about this? Or can't I use getCalendarItems() for this and only listChanges() ?

**Comment by jbostoen** [comment]
Does anyone know the solution to this?
