### ISSUE TITLE
$api->emptyTrash() -> RequestServerVersion error 

### ISSUE THREAD

**Issue by l0ckm4** [Garethp/php-ews#215]
Hi,

I am getting the following error when i try to empty the trash.

```
PHP Fatal error:  Uncaught SoapFault exception: [a:ErrorIncorrectSchemaVersion] The request is valid but does not specify the correct server version in the RequestServerVersion SOAP header.  Ensure that the RequestServerVersion SOAP header is set with the correct RequestServerVersionValue. in /Scripts/vendor/garethp/php-ews/src/API/NTLMSoapClient.php:119
Stack trace:
#0 /Scripts/vendor/garethp/php-ews/src/API/NTLMSoapClient.php(119): SoapClient->__call()
#1 /Scripts/vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(18): garethp\ews\API\NTLMSoapClient->__call()
#2 /Scripts/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(510): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}()
#3 /Scripts/vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(32): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}()
#4 /Scripts/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(510): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebSe in /Scripts/vendor/garethp/php-ews/src/API/NTLMSoapClient.php on line 119
```
Here is my code
```
use garethp\ews\API\Type;
use garethp\ews\MailAPI;

$host     = 'myexchangeserver';
$username = 'myusername';
$password = 'mypassword';

$api = MailAPI::withUsernameAndPassword($host, $username, $password);
$ret = $api->emptyTrash();
```
I can normally connect ok and its only the emptyTrash call that is throwing this error. I am connecting to an Exchange 2010 server.

Specifying the version in the MAILAPI call does not change the behaviour

`$api = MailAPI::withUsernameAndPassword($host, $username, $password, ["version" => 'Exchange2010']);`

Any ideas pls?

**Comment by l0ckm4** [comment]
I got it sorted - i have to specify the version as being Exchange2010_SP1 and not rely on it autodetecting.
