### ISSUE TITLE
UnauthorizedException when connecting to exchange accounts using - fromUsernameAndPassword - garethp - php-ews

### ISSUE THREAD

**Issue by rishilmusthafa** [Garethp/php-ews#227]
Fatal error:  Uncaught garethp\ews\API\Exception\UnauthorizedException in C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\API\ExchangeWebServices.php:454
Stack trace:
#0 C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\API\ExchangeWebServices.php(372): garethp\ews\API\ExchangeWebServices->handleNonSuccessfulResponses(NULL, 401)
#1 C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\API\ExchangeWebServices\MiddlewareFactory.php(57): garethp\ews\API\ExchangeWebServices->processResponse(NULL)
#2 C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\API\ExchangeWebServices.php(516): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#3 C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\API\ExchangeWebServices\MiddlewareFactory.php(66): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#4 C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\API\ExchangeWebServices.php(516): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#5 C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\API\ExchangeWebServices.php(526): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#6 C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\API\ExchangeWebServices.php(317): garethp\ews\API\ExchangeWebServices->executeMiddlewareStack(Array, Object(garethp\ews\API\MiddlewareRequest))
#7 C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\API.php(436): garethp\ews\API\ExchangeWebServices->__call('SyncFolderItems', Array)
#8 C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\CalendarAPI.php(197): garethp\ews\API->listItemChanges(Object(garethp\ews\API\Type\DistinguishedFolderIdType), NULL, Array)
#9 C:\xampp\htdocs\exemrms_mssql\test\test.php(11): garethp\ews\CalendarAPI->listChanges()
#10 {main}
  thrown in C:\xampp\htdocs\exemrms_mssql\test\vendor\garethp\php-ews\src\API\ExchangeWebServices.php on line 454

The above error is occurs please help me out

**Comment by braincept** [comment]
+1
